### ISSUE TITLE
Update the testing capabilities on JUnit by having testcontainers 

### ISSUE THREAD

**Issue by fokion** [marcinadd/projecty-web#43]
## Description

Add the test containers that will setup and tear down a database on each test. This will make the testing more reliable as it will use an actual database and not mocking.

## Requirements
- [x]  Explore and add the test containers dependency in the project
- [x] Convert at least one of the tests to prove the usefulness

**Comment by fokion** [comment]
@marcinadd I dont know why on the registration it was accepting the parameters as url encoded parameters on a POST request which was bizzare. I have updated the code to handle the POST body but the web project needs to be updated as well to reflect this change.

**Comment by marcinadd** [comment]
All mappings should be refactored to use JSON format. Another problem is the query parameters. Idk from where I took the idea of query params instead of URL params but it generates more issues than advantages. Today I'll create a new branch and try to edit them all for API, Web version and Android version as well. If all mappings in all apps will be changed the changes will be merged to default branches.

**Comment by marcinadd** [comment]
Merged
